### ISSUE TITLE
add support for custom ra declarations

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/randomizr#25]
need to add three args to `declare_ra`

1. custom_ra (a function that returns a vector of random assignments
2. permutation_matrix
3. sims

3 ways to declare a custom ra

1. custom_ra + sims.  sims defautls to 1000.  we estimate empriical probs of assignment by simulation.
2. custom_ra + permutation matrix.  No simulation needed; we estimate empirical probs of assignmetn from the permutation matrix
3. permutation matrix only.  The "random assignment function" is selecting one of the columns of the permutation matrix at random.

**Comment by graemeblair** [comment]
If we implemented this, this could simplify how we do declare_assignment because we could not exit the randomizr delegate for custom assignments. Maybe we should implement now?
