### ISSUE TITLE
Simple random assignment within blocks not allowed with declare_ra

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/randomizr#26]
As far as I can tell, `conduct_ra()` and `declare_ra()` do nothing with the `simple = T/F` flag if the design is blocked and nothing about simple vs. complete is stored in a declare object for blocked designs, other than in the `original_call` value which isn't accessed by `conduct_ra()`.

Unless you get a bad seed and the simple randomization returns complete randomization, this is a MWE:
```r
library(randomizr)

## Not blocked, works as expected, information about simple stored in 'ra_type'
d <- declare_ra(N = 1000)
d$ra_type # returns 'complete'
table(conduct_ra(d))

d <- declare_ra(N = 1000, simple = T)
d$ra_type # returns 'simple'
table(conduct_ra(d))

## Block, does not work as expected
block <- rep(1:2, times = c(500, 500))

d_block_simp <- declare_ra(N = 1000, block_var = block, simple = T)
d_block_simp$ra_type
d_block_comp <- declare_ra(N = 1000, block_var = block, simple = F)
d_block_comp$ra_type
# information only stored in 'original_call' which is never used elsewhere in randomizr

y_simp <- conduct_ra(d_block_simp)
table(y_simp) # rerun it, always 0.5/0.5
y_comp <- conduct_ra(d_block_comp)
table(y_comp)
```

Is this the preferred behavior or should you allow SRS within blocks? How should that information be stored?

**Comment by lukesonnet** [comment]
e: my MWE had some typos, fixed now on github case you are getting this via email.

**Comment by lukesonnet** [comment]
Looking at the code for `declare_ra()`, it appears the only place the simple flag is stored is in the `ra_function` value, and if there is any blocking, it doesn't pass on the simple flag.

**Comment by graemeblair** [comment]
@lukesonnet should we address this now before submission?

**Comment by lukesonnet** [comment]
It needn't be, as it appears that I can retrieve the information from `original_call` in the resulting list. However, it seems like the result should be more transparent about whether the randomization is complete or simple.

**Comment by graemeblair** [comment]
@nfultz @lukesonnet perhaps you could coordinate on making this change before we push it to CRAN?
