### ISSUE TITLE
Drop partition dependency

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/randomizr#27]
Right now, `randomizr` pulls in the partitions package for one function. We may be able to reimplement it.

Convo from slack:

> So I'm taking at quick look at your use of `partitions`, it looks like you only import `restrictedparts` - thoughts below
> 
> * That function is backed by a C implementation - it is probably pretty fast - https://github.com/cran/partitions/blob/master/src/partitions.c#L222
> * He's calling through the legacy `.C` interface instead of the better `.Call` interface - this can  be slow for large inputs
> * References `/* algorithm on p232 of Andrews */` - do you know what that is?
> * None of the C is using lin/lapack - everything is procedural scalar arithmetic and it's speed really will depend on how optimized the compiler can get it- there's a decent chance that a pure R implementation that used matrix math properly would outperform it - an RcppArmadillo implementation has an even better chance.
> * partitions is GPL, randomizr is MIT, so you probably shouldn't copy-paste the functions into randomizr.
> GitHub
> cran/partitions
> :exclamation: This is a read-only mirror of the CRAN R package repository. partitions — Additive Partitions of Integers
>  
> 
> Found it ` `• G. E. Andrews. "The theory of partitions", Cambridge University Press, 1998`

**Comment by aaronrudkin** [comment]
Leaving a comment to indicate this was discussed at our weekly meeting, and everyone is on board with killing the dependency.

**Comment by graemeblair** [comment]
Can't this be closed @nfultz ?

**Comment by nfultz** [comment]
Yes, this is done.
