### ISSUE TITLE
Re-do errors a la Hadley

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/randomizr#37]
In particular, I think we should adopt the

"cant / must" language

and the backticks

http://style.tidyverse.org/error-messages.html

**Comment by graemeblair** [comment]
Great.

Related, @nfultz can I suggest as we deploy these that you update https://github.com/DeclareDesign/DeclareDesign/wiki with a couple of the things we seem to be doing across packages before pushing, i.e. versioning and error messages.
