### ISSUE TITLE
Clarify ordering of block probs in documentation

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/randomizr#70]
Help is not too clear on order in which to specify block probs. Same for block_prob_each. 

Appears to depend on `sort` order. eg:

```
> b <- sample(rep(c("a", "d", "_b", 2), 100))
> z <- block_ra(b, block_prob = (1:4)/4)
> table(b, z)
    z
b      0   1
  _b  75  25
  2   50  50
  a   25  75
  d    0 100 
```

**Comment by acoppock** [comment]
The help file for block_m_each reads: 
```
The rows should respect the ordering of the blocks as determined by sort(unique(blocks)). The columns should be in the order of conditions, if specified.
```
I could add something similar to the other arguments that have "rows"?

**Comment by macartan** [comment]
Yes great; was focused on block_prob but think redundancy here is no harm
