### ISSUE TITLE
Assigning block probs after sampling

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/randomizr#71]
Dealing with a situation where blocks may be empty (this could happen with some sampling,  though in current application because blocks are based on XY combinations some of which may be empty).

Can we link block probs to blocks using factors? Or perhaps have block_probs calculated from a column of unit level probs.

```
#OK
blocks = factor(rep(4:1, each = 2))
block_ra(blocks, block_prob = c(1:4)/4)

# Not OK
blocks = blocks[3:8]
block_ra(blocks, block_prob = c(1:4)/4)
```

**Comment by acoppock** [comment]
Can you adjust your code so that block_prob is always the correct length?

**Comment by macartan** [comment]
this would mean figuring out which blocks are present and then subsetting
the probability vector; certainly possible but not I think preferable to
being able to specify the probabilities directly by name

**Comment by acoppock** [comment]
Yes, I think that approach is safer than relying on factors to know which blocks have no units in them.

**Comment by macartan** [comment]
imagine there are a few ways to do it, but would be good as part of
block_ra and not left to users to figure this out
not sure why using factors not safe, but using names or block probs could
be another approach if there were a fix like the below inside the functon
(when names exist)

> block_prob = c(A = .4, B = .3, C = .3, D = .2)> > blocks = c("A", "B", "B", "A")> > block_prob <- block_prob[names(block_prob) %in% blocks]>   > block_prob  A   B
0.4 0.3



i

**Comment by acoppock** [comment]
I'm not sure what you mean by "left to users to figure out" -- they pass a vector of blocks and provide parameters in the order of those blocks.  I don't think it's crazy to not support users who pass parameter information for blocks that don't exist in the vector of blocks passed to block_ra

**Comment by macartan** [comment]
I think it's not a lot for users to want to want to be able to give a
direct mapping between block ids and block probabilities without having to
rely on a sort order in a possibly changing set. Will suggest some code.

**Comment by acoppock** [comment]
Ok thats great. whatever the solution, it should *not* break assigning by order

**Comment by acoppock** [comment]
I think that the new `prob_unit` and `m_unit` arguments will address this problem.  Those will be vectors of length `N`, so if you subset your data, then the parameters won't need to be updated.  Or maybe I'm mis understanding?
