### ISSUE TITLE
Suggested feature: nearest-neighbor matching for continuous variables

### ISSUE THREAD

**Issue by daaronr** [DeclareDesign/randomizr#82]
(Apologies if there's a way to do this that I missed; maybe this is something for the blockTools package, but I cannot understand how to 'exact' block on some variables and nearest-match on others in that package).

Suppose I want to block-randomize on Gender and Race, and then within these categories 'alternate' assignment by Age, so that within any small window of Age we will have an even balance of Control and Treatment(s). Is this do-able through your (great!) package? I could not find it in the docs.

**Comment by acoppock** [comment]
Thanks @daaronr -- no you're right that this is something for the blockTools package.  Randomizr won't make blocks for you... but it'll randomize if you've already got a variable for blocking.  Blocktools has a good way to do it https://gist.github.com/acoppock/89483cdce68867f8ee88e1f5cd2f318b

I'd also suggest checking out quickblock: https://github.com/fsavje/quickblock.
